command: ["streamlit", "run", "app.py"]

env:
  - name: "AZURE_TENANT_ID"
    valueFrom: "azure-b2c-tenant-id"
  - name: "AZURE_CLIENT_ID"
    valueFrom: "azure-b2c-client-id"
  - name: "AZURE_CLIENT_SECRET"
    valueFrom: "azure-b2c-client-secret-id"
